### ISSUE TITLE
공통 컴포넌트 Profile - 수정 요청 

### ISSUE THREAD

**Issue by hwiiron** [codeit-sprint-part2-2team/rolling#118]
공통 컴포넌트의 Profile 수정 요청드립니다.

## Profile.jsx
`onClick`으로 프로필 이미지를 리턴 받아서 상태를 업데이트 하기 위해 추가되었습니다.
`onProfileImgClick` 해당 함수명은 제 임의대로 작성한 부분이라 수정하셔도 됩니다!

```
Profile.propTypes = {
  imageURL: PropTypes.string,
  size: PropTypes.oneOf(['s', 'm']),
  onClick: PropTypes.func,
};

function Profile({ imageURL, size = 's', onClick }) {
  const IMG_URL = imageURL || DEFAULT_IMAGE;

  const onProfileImgClick = () => onClick(IMG_URL);

  return (
    <ProfileArea size={size}>
      <img
        src={IMG_URL}
        alt="프로필"
        onClick={onClick ? onProfileImgClick : undefined}
      />
    </ProfileArea>
  );
}
```

### 위 내용이 이해가 안 되시는 부분이 있다면 바로 알려주세요!!

**Comment by swp91** [comment]
온클릭으로 프로필 이미지 URL을 전달받는 의도라고 보면될까요?

**Comment by hwiiron** [comment]
> 온클릭으로 프로필 이미지 URL을 전달받는 의도라고 보면될까요?

네 맞습니다! 이미지 URL을 전달받아서 프로필 이미지 선택할때마다 좌측의 이미지가 변경되도록 하려고 합니다!
![Group 3](https://github.com/user-attachments/assets/df3ea584-35f3-4e1a-8475-db206d3a051a)

그리고 아래 코드는 클릭 이벤트가 없는 이미지를 클릭 했을 경우에 에러가 나서 추가했습니다!
```
onClick ? onProfileImgClick : undefined
```
