### ISSUE TITLE
Profile 컴포넌트 이미지 노출 안됨

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#119]
### 이슈 사항
- Profile 컴포넌트에 이미지를 넣었는데 변경되지않고 기본값으로 노출됩니다.
### 이슈 재현
- imageUrl 값으로 `'https://ifh.cc/g/YPcyrk.png'` 을 전달한 것을 확인했지만 실제 이미지가 아닌 기본값으로 노출됩니다.
- 실제 다른 이미지 URL을 받아서 테스트 해봐야 할 것 같습니다.
- 해당 이미지 URl로 POST 했을때 정상적인 URl임을 확인했습니다.
![스크린샷 2024-10-29 오후 2 39 31](https://github.com/user-attachments/assets/1c4fc8e6-be53-4158-b373-b751b9504fe9)

**Comment by junghwa1996** [comment]
엇 잠시만요 제가 뭔가 잘못 넣은것같기도 해요

**Comment by junghwa1996** [comment]
앗 제가 실수했네요..ㅎㅎㅎㅎㅎㅎㅎ

**Comment by swp91** [comment]
이슈 설명부분 오타 죄송합니다.. PR 설명엔 수정했는데 작업하면서 props명 달라진점을 따로 고지하지 않아서 생긴 문제인것같습니다 흑흑
