### ISSUE TITLE
Textarea 컴포넌트 수정 요청

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#135]
## 이슈 사항
- textarea width와 height를 지정할 수 없어요 🫠
- StyledTextarea가 export 되어있지 않습니당..
- width랑 height와 padding은 rem 단위로도 수정해주세요!!
- 파일도 별도 분리안되어있어요! 스타일파일 별도 분리 부탁드려요!

이거 제가했어용ㅎ 메세지 컴포넌트 PR 시 같이 올릴게용

**Comment by junghwa1996** [comment]
소망님 이거 제가 알아버렸어요....Textarea 기능 컴포넌트 자체가 필요없다는거... 그냥 스타일 컴포넌트만 만들면 되는거였어요..그러면 굳이 두번이상 props를 내려주지않아도되구요....충격..!! 
그래서 이번에 메세지 카드 컴포넌트 작업하면서 조금 리팩토링 하다가 알게된건데 Textarea.jsx는 안쓸것같아서 지워주시면될것같고 대신 Textarea.styles.js는 좀만 손봐서 메세지 리스트 페이지로 가져올게요..!!

**Comment by mangmang1004** [comment]
넵넵 정화님 !!! ... 확인했습니당 :-) 제가 휘철님 input 작업할 때 Textarea.jsx도 같이 지울게용 ! 감사해융

**Comment by junghwa1996** [comment]
> 넵넵 정화님 !!! ... 확인했습니당 :-) 제가 휘철님 input 작업할 때 Textarea.jsx도 같이 지울게용 ! 감사해융

앗 이미 카드 작업내역에 있어서 안지우셔도됩니다 ㅎㅎ 지운상태로 머지됐을꺼에용
