### ISSUE TITLE
Outlined 컴포넌트 에러

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#136]
```
hook.js:608 Warning: React does not recognize the `iconPosition` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `iconposition` instead. If you accidentally passed it from a parent component, remove it from the DOM element. Error Component Stack
```

## 버그 재현
- 전 해당 iconPosition 옵션 안썼는데 에러뜨네용 확인하고 수정해주세용

**Comment by swp91** [comment]
에구 이런 에러가 뜨는군요
혹시 어떤 상황에서 뜨는지 알려주실 수 있을까요?

**Comment by junghwa1996** [comment]
> 에구 이런 상황이 시작된다면 어떤 상황에서 시작할 수 있는지 확인할 수 있나요?

onClick 이벤트 넣으니까 발생했던 것 같구요! 해당 에러가 iconPosition 네임의 props를 전달할때, DOM에 전달하지않고 스타일 컴포넌트에 전달할 수 있게끔 해달라 라는 오류에영!! 앞에 $ 기호 붙히면 해결될듯합니당
