### ISSUE TITLE
Outlined 경고문 이슈 & 버튼 모양 이상해짐

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#156]
## 문제1
- 제가 이번에 작업한 메세지 리스트 페이지 가보시면 콘솔에러떠있는데 확인 한번 부탁드려요!
- 저번에 말했던 이슈와 동일함 (#136 )
- 이거 확인해보니까 지금 props name에도 $를 붙혀주셔야하는데 안붙어있더라구용 ㅠㅠ 

## 문제2
- 저는 버튼설정을 따로 건든적이없는데 페이지 작업하고 보니까 버튼이 찌부됐어용 ㅠㅠ 
- 그리고 스타일 단위도 px이던데 하시는김에 이것도 변경해주세용

## 이슈 재현
#155 해당 브랜치 가셔서 
MessagesListPage > MessageCardList type props를 edit으로 변경해서 확인해주세요!! 

## 캡쳐본
![스크린샷 2024-10-30 오후 10 10 01](https://github.com/user-attachments/assets/28cca2da-6956-4149-b1fd-5f12cf187403)

**Comment by swp91** [comment]
헉 이런일이..! 확인해보겠습니다

**Comment by junghwa1996** [comment]
> 헉 이런일이..! 확인해보겠습니다

일반 뱃지 폰트사이즈랑 border-radius 도 적용이 안되고있는것같아요 ㅠㅠㅠ이것도 같이 확인해주세요!!

**Comment by swp91** [comment]
넵 요것도 확인해서 같이 처리하겠습니다!

**Comment by junghwa1996** [comment]
이거 언제 완료될까요??

**Comment by swp91** [comment]
네 지금 PR 올리겠습니다

**Comment by junghwa1996** [comment]
> 네 지금 PR 올리겠습니다

넹 올려주시면 바로 확인하겠습니당!
