### ISSUE TITLE
삭제하기 메시지 리스트

### ISSUE THREAD

**Issue by Hogn-hyeonbin** [codeit-sprint-part2-2team/rolling#160]
- [x]  화면에 3열 2행 메시지 카드 구성

- [ ] 무한 스크롤 기능 구현

- [x] 메시지 카드 컴포넌트에 수정,삭제 아이콘 추가
- [ ] 휴지통 아이콘 클릭시 메시지 삭제
- [ ] 수정 아이콘 클리시 수정하기 페이지로 이

**Comment by junghwa1996** [comment]
무한 스크롤이랑 삭제, 수정 시 페이지 이동하여 데이터 로드 기능 만 작업해주세요!
지금 제가 컴포넌트 작업하면서 MessagesListPage 컴포넌트로 공통으로 사용할수있게 작업중이에요!

**Comment by junghwa1996** [comment]
거의 다되어갑니다!! 곧 PR 올릴게요!!

**Comment by junghwa1996** [comment]
해당 컴포넌트 작업 완료되어서 PR 올렸습니다 확인해주세요! #167
