### ISSUE TITLE
메세지 추가하기 페이지 스타일 요소 DOM 접근 에러

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#168]
## 이슈
- 지금 메세지 추가하기 페이지 가면 스타일 요소 DOM 접근 에러가 뜹니다!! 이게 어느 컴포넌트에서 발생하는건지 몰라서 담당자인 @hwiiron 님 언급드리고 휘철님이 확인 하신 후에 해당 담당자 분께 리마인드 드리면 될것같습니다

# 이슈 화면
![스크린샷 2024-10-31 오후 5 40 58](https://github.com/user-attachments/assets/3f1e8ea9-0e0e-480c-8e81-45909d3d50c5)

**Comment by hwiiron** [comment]
해당 내용 인지하고 있습니다.. 이 부분 지금 텍스트 에디터에서 에러가 나고 있는 것 같은데 제가 지금 하고 있는 부분만 마무리하고 확인해 보겠습니다!
