### ISSUE TITLE
layout-Emoji(이모지 선택기능)

### ISSUE THREAD

**Issue by yongcheol-1** [codeit-sprint-part2-2team/rolling#201]
- [x] EmojiPickerComponent.jsx
- [x] EmojiPickerComponent.module.css
- [x] EmojiPickerComponent.sytles.js

**Comment by junghwa1996** [comment]
이거 작업은 조금 후순위로 두실 수 있나용? 기능 작업 끝나면 말씀드릴게요!

**Comment by junghwa1996** [comment]
요것은 제가 완료했습니다룽!
