### ISSUE TITLE
components-MessagesCardList(메시지 카드 리스트 컴포넌트)

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#204]
### MessageCard
#207 
### MessageCardList
- [x] MessageCardList
- [x] MessageCardList.styles
- [x] StyledCreatedAt.styles
- [x] StyledTextarea.styles

### MessagesHeader
#206

**Comment by junghwa1996** [comment]
@Hogn-hyeonbin 여기서 작업해주세요~

**Comment by Hogn-hyeonbin** [comment]
> @Hogn-hyeonbin 여기서 작업해주세요~

넵 알겠습니다!

**Comment by junghwa1996** [comment]
> > @Hogn-hyeonbin 여기서 작업해주세요~
> 
> 넵 알겠습니다!

아 이거는 메세지 리스트 스타일이고 잠시만용 헷갈렸네여

**Comment by mangmang1004** [comment]
이 부분에서 반응형도 아직 작업이 되어야 하는 중인가융??

**Comment by junghwa1996** [comment]
> 이 부분에서 반응형도 아직 작업이 되어야 하는 중인가융??

반응형작업은 완료됐고 리팩토링만 진행하면됩니다~
