### ISSUE TITLE
관리자 모드 버튼 패스워드로 Edit로 이동

### ISSUE THREAD

**Issue by hwiiron** [codeit-sprint-part2-2team/rolling#220]
관리자 모드 버튼 생성하여 패스워드 입력하고 조건 성립 시 Edit로 이동

---

### 롤링 페이퍼 페이지에서 관리자 체크 후, 수정 페이지로 이동할 경우에 발생하는 문제
롤링 페이퍼 페이지를 거치지 않고, URL로 직접 수정 페이지 접근하면 접근 가능

### 해결 방안
1. 롤링 페이퍼에서 수정하기(관리자모드?) 버튼 클릭 시, 해당하는 수정 페이지로 이동
2. 수정 페이지 접근 시, 곧바로 `prompt`로 관리자 비밀번호 체크
- 검증 성공 시 : 수정 페이지 접근
- 검증 실패 시 : 이전  페이지로 이동 - `useNavigate(-1)`

수정 페이지 접근 시, 곧바로 모달 창 띄우고 관리자 체크가 가능하나, 개발자 모드로 모달 창 걷어내면 접근이 가능하며,
유저 검증 시스템이 없이는 완벽하게 수정 리스트, 상세 페이지를 접근할 수 없게 구현은 불가능할 것 같습니다.

`prompt`를 사용하는 방식은 작업은 완료되었지만 우선은 홀드하고, 내부 회의를 통해 결정하도록 하겠습니다.

---

모달 창으로 검증 실패 시, 수정 리스트 컴포넌트를 리턴 시키지 않는 방법도 가능할 것 같습니다.

**Comment by junghwa1996** [comment]
진행사항 공유부탁드립니다

**Comment by hwiiron** [comment]
> 진행사항 공유부탁드립니다

현재 메시지 리스트 페이지에서 제가 임의로 생성한 수정하기 버튼을 클릭 시 `/edit` 페이지로 이동하며, 곧바로 `prompt` 통하여 검증하여 검증이 성공하면 접근, 실패하면 이전 페이지로 되돌아 가도록 구현되어 있습니다. 

해당 내용 아직 PR을 올리지 않았지만 위 내용 구현 방법으로 우선 적용을 원하시면 바로 PR 올리도록 하겠습니다.

**Comment by junghwa1996** [comment]
> > 진행사항 공유부탁드립니다
> 
> 현재 메시지 리스트 페이지에서 제가 임의로 생성한 수정하기 버튼을 클릭 시 `/edit` 페이지로 이동하며, 곧바로 `prompt` 통하여 검증하여 검증이 성공하면 접근, 실패하면 이전 페이지로 되돌아 가도록 구현되어 있습니다.
> 
> 해당 내용 아직 PR을 올리지 않았지만 위 내용 구현 방법으로 우선 적용을 원하시면 바로 PR 올리도록 하겠습니다.

스타일은 추후 진행해도되니 기능 먼저 PR 올려주시면 감사하겠습니다~
