### ISSUE TITLE
롤링 최신순,인기순 에러 발생

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#224]
![스크린샷 2024-11-02 오후 5 27 16](https://github.com/user-attachments/assets/4eacfb23-b367-49d0-9629-1ffaea0918ed)

# 문제
- [ ] 최신순과 인기순으로 나와야하는데 인기순 기준으로만 나옴 [issue target](https://github.com/codeit-sprint-part2-2team/rolling/blob/099794feba88a9d321007830b8c86f1c86367947/src/pages/RecipientsList/RecipientsList.jsx)

**Comment by junghwa1996** [comment]
이거 얼마나 남았나요?

**Comment by Hogn-hyeonbin** [comment]
> 이거 얼마나 남았나요?

저 지금 작업 중이어서 11시까지는 가능 할 것 같습니다!

**Comment by junghwa1996** [comment]
> > 이거 얼마나 남았나요?
> 
> 
> 
> 저 지금 작업 중이어서 11시까지는 가능 할 것 같습니다!

넵 확인했습니당
