### ISSUE TITLE
버튼 사이즈 다름

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#237]
![image](https://github.com/user-attachments/assets/852f6c22-e776-40c7-9162-4d185150a654)

- 여기 edit인데 버튼 사이즈가 갑자기 커졌어요 `size='s'`

**Comment by swp91** [comment]
제 테스트 환경에선 괜찮은것 같은데
혹시 상속같은 다른 문제로 인한 이슈인것 같습니다! 확인 한번 부탁드리겠습니다
