### ISSUE TITLE
롤링 페이퍼, 메시지 생성 로딩 추가

### ISSUE THREAD

**Issue by hwiiron** [codeit-sprint-part2-2team/rolling#239]
- [x] MessageAddPage.jsx
- [x] RecipientsAppPage.jsx

---

연결된 이슈 : #246

**Comment by junghwa1996** [comment]
진행사항 공유 부탁드립니다

**Comment by hwiiron** [comment]
> 진행사항 공유 부탁드립니다

롤링 페이퍼, 메시지 생성 페이지 로딩 로직은 추가하였고, 아직 PR은 올리기 전입니다.

버튼에 로딩스피어를 추가하여 생성 중인 상황을 알리는 것이 좋을 것으로 판단되어, @swp91 님께 다른 작업이 완료되면 버튼에 loding prop 내려줄 수 있는 부분과 로딩 스피어 부탁드리고 홀드 상태입니다.

**Comment by junghwa1996** [comment]
> > 진행사항 공유 부탁드립니다
> 
> 롤링 페이퍼, 메시지 생성 페이지 로딩 로직은 추가하였고, 아직 PR은 올리기 전입니다.
> 
> 버튼에 로딩스피어를 추가하여 생성 중인 상황을 알리는 것이 좋을 것으로 판단되어, @swp91 님께 다른 작업이 완료되면 버튼에 loding prop 내려줄 수 있는 부분과 로딩 스피어 부탁드리고 홀드 상태입니다.

그럼 선행 작업 이슈 해당 이슈에 연결 부탁드려요~
