### ISSUE TITLE
에러 발생 시 화면 구현

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#244]
### 내용
- [close.svg](https://github.com/codeit-sprint-part2-2team/rolling/blob/8fc68b541b1c1eced50a12d6b95fab71c5f9274a/src/assets/close.svg) 이용하여, var(--error) 컬러 배경을 가진 모양으로 상단에는 서버 응답 에러코드 띄어주시고 '에러가 발생했습니다' 페이지 노출
- '뒤로가기' 버튼 생성 후 뒤로가기 클릭 시 이전 페이지로 넘어가기
- 안에 에러 텍스트는 유저가 원하는 값으로 변경 할 수 있게끔 컴포넌트 제작

- [x] error 버튼 컴포넌트 제작
- [x] error 페이지 구현
- [x] 고의로 에러를 일으켰을때 서버 응답 에러코드 정상적으로 띄어주는지 확인
- [x] '뒤로가기' 기능 구현
### 예시
https://www.figma.com/design/wzldDm4XYZy9FavYHu7J9X/%EB%A1%A4%EB%A7%81%5B%EA%B8%B0%EB%8A%A5-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EA%B8%B0%ED%9A%8D%5D?node-id=98-8040&t=TP9Ckn6xXXWov4WC-4

**Comment by Hogn-hyeonbin** [comment]
확인했습니다!
