### ISSUE TITLE
파일 구조화 후 스켈래톤 컴포넌트 제작

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#245]
- [x] MessagesList @junghwa1996 #247 
- [x] RecipientsList @hwiiron  #248 
---
## PR
- 각자 페이지에 이슈 생성해주시고 이름 뒤에 이슈 연결 부탁드립니다!
- PR 요청은 해당 브랜치에 부탁 드립니다
- 최종 PR은 제가 올리겠습니다
## 참고
https://github.com/codeit-sprint-part2-2team/rolling/blob/456f3400ea38167cbfc450d4d9f10b9eccb6a962/src/components/CardComponents/Skeleton

**Comment by mangmang1004** [comment]
그런데 홈페이지의 경우 데이터를 비동기로 받아오는 게 없는데 스켈레톤을 제작을 할 필요가 있을까요 ??!

**Comment by junghwa1996** [comment]
> @junghwa1996 @hwiiron 그런데 홈페이지의 경우 데이터를 비동기로 받아오는 게 없는데 스켈레톤을 제작을 할 필요가 있을까요 ??!

저희가 styled components를 좀 많이 쓰고있어서 최대한 퍼포먼스 챙기려고 그런거에요!
비동기 처리부분이 없어서 노출이 어렵다면 `setTimeout`써서 해보면 어떨까요??

**Comment by mangmang1004** [comment]
오오 좋네요 !! 이해했습니당 !

**Comment by junghwa1996** [comment]
메세지 리스트는 무한스크롤 때문에 오히려 오류로 보여서 제거하기로 함.
