### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#299]
![image](https://github.com/user-attachments/assets/fe987e1c-bc79-4c2a-b144-e6346054904f)

- [x] 콘솔 `isLocation` error 발생
- [x] /components/DarkModeToggle/DarkModeToggle.jsx
- [x] /components/TotalMessage/TotalMessage.jsx
- [x] /components/TotalMessage/TotalMessage.styles.js

추가 + 빌드에러

```
src/pages/RecipientsList/RecipientsList.jsx
  Line 16:8:   'Loading' is defined but never used             no-unused-vars
  Line 31:10:  'isLoading' is assigned a value but never used  no-unused-vars
```

**Comment by hwiiron** [comment]
해당 이슈 처리하고 `push`했습니다!

**Comment by junghwa1996** [comment]
merge 완료
